version: '3'
services:
  server:
    container_name: server
    build: server/
    ports:
      - '5000:5000'
    volumes:
      - /var/lib/mongodb:/data/db
  client:
    container_name: client
    build: client/
    restart: always
